name: GitHub Actions compare branches
on:
   workflow_dispatch: {}
#    schedule:
#       - cron: "*/5 * * * *"
env:
 USERNAME: "sukanya"
 EMAIL: "sukanya5960@gmail.com"
 ORIGIN_BRANCH: main
 MERGE_BRANCH: stage1
 
jobs:
  compare:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Compare Master and Staging
        id: branch-compare
        run: ${PWD}/ci/branch-compare.sh
      - name: Send custom JSON data to Slack workflow
        if: steps.branch-compare.outputs.COMPARE_RESULT != null
        id: slack
        uses: slackapi/slack-github-action@v1.23.0
        with:
          # For posting a rich message using Block Kit
          payload: |
            {
              "text": "Compare branches result",
              "blocks": [
                {
                  "type": "section",
                  "text": {
                    "type": "mrkdwn",
                    "text": "<@U047ARJGWH1>  :loudspeaker: Comparison result of ${{ env.ORIGIN_BRANCH }} branch and ${{ env.MERGE_BRANCH }} branch is: ${{ steps.branch-compare.outputs.COMPARE_RESULT }}"
                  }
                }
              ]
            }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
          SLACK_WEBHOOK_TYPE: INCOMING_WEBHOOK
       
          
