name: CI PR RC

on:
  workflow_dispatch: {}
  pull_request:
    branches:
      - rc_test
    types:
      - opened
      - synchronize
      - labeled
      - reopened

jobs:
  build-and-deploy-dev-preview:
    if: github.base_ref == 'main'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run a one-line script
        run: echo Hello, world!
