name: CI

on:
  pull_request:
    branches:
      - main
    types:
      - opened
      - synchronize
      - labeled
#test
jobs:
  build:
    if: ${{ contains(github.event.pull_request.labels.*.name, 'prod-preview') }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run a one-line script
        run: echo Hello, bug!
      
  build-and-deploy-dev-preview:
    if: github.base_ref == 'main'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run a one-line script
        run: echo Hello, world!
